# Generated by Django 5.0.2 on 2024-06-12 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='Status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('completed', 'Completed')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue_Type', models.CharField(choices=[('missed pickup', 'Missed pickup'), ('poor service', 'Poor service')], max_length=30)),
                ('Complaint', models.TextField()),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('withdrawn', 'Withdrawn')], max_length=30)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
