# Generated by Django 5.0.2 on 2024-07-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_issues_schedule_vehicle_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='drivers_license',
            new_name='driver_license',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pickup_days',
            field=models.JSONField(default=dict),
        ),
    ]
