# Generated by Django 5.0.2 on 2024-04-24 13:01

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('other_names', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('mobile_phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_of_birth', models.DateField()),
                ('user_type', models.CharField(choices=[('domestic', 'Domestic'), ('business', 'Business')], default='domestic', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_driver', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('other_names', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile_phone', models.CharField(max_length=15, null=True)),
                ('driver_license_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_driver', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('missed pickups', 'Missed pickups'), ('poor service', 'Poor service')], default='missed pickups', max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[(core.models.IssueStatus['PENDING'], 'Pending'), (core.models.IssueStatus['RESOLVED'], 'Resolved')], max_length=13)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=30)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('daily', 'Daily')], default='weekly', max_length=20)),
                ('days', core.models.PickUpDaysField(blank=True, choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=50)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('License_plate_number', models.CharField(max_length=11)),
                ('capacity_litres', models.FloatField()),
                ('Driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[(core.models.PickUpStatus['PENDING'], 'Pending'), (core.models.PickUpStatus['COMPLETED'], 'Completed')], max_length=13)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.driver')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schedule')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle')),
            ],
        ),
    ]
